package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"
)

// initAnswers is the resolved set of choices from `lantern init`'s prompts.
// Each field maps directly onto one or more Helm subchart toggles -- see
// renderValues.
type initAnswers struct {
	Metrics  bool // kube-prometheus-stack (Prometheus, Alertmanager, Grafana, node-exporter)
	Logs     bool // loki + logsCollector
	Traces   bool // tempo
	SDKAgent bool // opentelemetry-operator; only asked/meaningful if Traces
	GPU      bool // gpuMonitoring (ServiceMonitor/PrometheusRule only -- dcgm-exporter itself is bring-your-own)
}

// collectorNeeded reports whether the OTel Collector subchart is needed at
// all. It's the thing every other signal actually routes through: logs and
// traces both get pushed to it via OTLP, and so does SDK/agent
// instrumentation's own export path. Plain Prometheus scrape-based metrics
// never touch it.
func (a initAnswers) collectorNeeded() bool {
	return a.Logs || a.Traces || a.SDKAgent
}

// promptYesNo asks a yes/no question with a default, reading from r one line
// at a time and writing the prompt (and any re-prompt on bad input) to w.
// Empty input accepts the default -- this is what lets a user hammer enter
// through the whole flow and get the "everything" quickstart back.
func promptYesNo(r *bufio.Reader, w io.Writer, question string, def bool) (bool, error) {
	suffix := "[Y/n]"
	if !def {
		suffix = "[y/N]"
	}
	for {
		fmt.Fprintf(w, "%s %s ", question, suffix)
		line, err := r.ReadString('\n')
		if err != nil && line == "" {
			return false, err
		}
		switch strings.ToLower(strings.TrimSpace(line)) {
		case "":
			return def, nil
		case "y", "yes":
			return true, nil
		case "n", "no":
			return false, nil
		}
		fmt.Fprintln(w, "please answer y or n")
	}
}

// runInitPrompts asks the questions and returns the answers. Separated from
// terminal I/O so it's testable with a canned reader/writer, matching this
// package's existing style (reorderArgs/render are pure, main just wires
// them to os.Args/os.Stdin).
func runInitPrompts(r io.Reader, w io.Writer) (initAnswers, error) {
	br := bufio.NewReader(r)
	var a initAnswers
	var err error

	fmt.Fprintln(w, "lantern init — a few questions, then I'll write a values file with only what you asked for.")
	fmt.Fprintln(w, "Press enter to accept the default (capital letter) at any prompt.")
	fmt.Fprintln(w)

	if a.Metrics, err = promptYesNo(br, w, "Metrics (Prometheus + Grafana)?", true); err != nil {
		return a, err
	}
	if a.Logs, err = promptYesNo(br, w, "Logs (Loki)?", true); err != nil {
		return a, err
	}
	if a.Traces, err = promptYesNo(br, w, "Traces?", true); err != nil {
		return a, err
	}
	if a.Traces {
		if a.SDKAgent, err = promptYesNo(br, w,
			"  Real SDK/agent instrumentation too? (deeper spans -- DB queries, route\n"+
				"  detail -- but restarts each instrumented service's pods, one at a time,\n"+
				"  and needs a known runtime. Answering no keeps eBPF only: zero per-service\n"+
				"  config, no pod restarts, shallower spans.)",
			false); err != nil {
			return a, err
		}
	}
	if a.GPU, err = promptYesNo(br, w, "GPU node monitoring (DCGM)? Skip if you have no GPU nodes.", false); err != nil {
		return a, err
	}

	return a, nil
}

// traceLokiDataSources returns the Grafana additionalDataSources entries
// (pre-rendered as YAML list-item text) for whichever of Tempo/Loki are
// actually enabled, in the exact shape values-quickstart.yaml itself uses --
// same UIDs (tempo-main, loki-main) so anything else in the chart that
// references those UIDs (per-service dashboards, the Investigate-style
// dashboards) keeps working unmodified.
func traceLokiDataSources(a initAnswers) []string {
	var out []string
	if a.Traces {
		out = append(out, "      - name: Tempo\n        type: tempo\n        uid: tempo-main\n"+
			"        url: http://lantern-tempo.observability:3200\n        access: proxy\n")
	}
	if a.Logs {
		out = append(out, "      - name: Loki\n        type: loki\n        uid: loki-main\n"+
			"        url: http://lantern-loki.observability:3100\n        access: proxy\n")
	}
	return out
}

// renderValues writes the Helm values overlay for the given answers. It's
// deliberately small: just the enable/disable toggles, meant to be layered
// on top of values-quickstart.yaml (which already carries the resource
// sizing and install-ordering fixes found running this chart against a real
// cluster) rather than duplicating that tuning here.
func renderValues(a initAnswers) string {
	var b strings.Builder
	b.WriteString("# Generated by `lantern init`. Layer this on top of values-quickstart.yaml --\n")
	b.WriteString("# it only carries the enable/disable decisions from your answers, not the\n")
	b.WriteString("# resource sizing or install-ordering fixes already in that file.\n#\n")
	b.WriteString("#   helm install lantern charts/lantern-stack \\\n")
	b.WriteString("#     -f charts/lantern-stack/values-quickstart.yaml \\\n")
	b.WriteString("#     -f <this-file>\n\n")

	fmt.Fprintf(&b, "kube-prometheus-stack:\n  enabled: %v\n", a.Metrics)
	if a.Metrics {
		// values-quickstart.yaml wires Tempo and Loki into Grafana as fixed
		// additionalDataSources regardless of whether those subcharts are
		// enabled -- pointing Grafana at services that don't exist if you
		// turned traces/logs off. Helm replaces (doesn't merge) list values
		// across -f files, so this override corrects it to match what's
		// actually installed. Found by actually rendering a metrics-only
		// combination and grepping the output for "tempo"/"loki", not
		// assumed.
		datasources := traceLokiDataSources(a)
		if len(datasources) == 0 {
			b.WriteString("  grafana:\n    additionalDataSources: []\n")
		} else {
			b.WriteString("  grafana:\n    additionalDataSources:\n")
			for _, ds := range datasources {
				b.WriteString(ds)
			}
		}
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "loki:\n  enabled: %v\n\n", a.Logs)
	fmt.Fprintf(&b, "logsCollector:\n  enabled: %v\n\n", a.Logs)
	fmt.Fprintf(&b, "tempo:\n  enabled: %v\n\n", a.Traces)
	fmt.Fprintf(&b, "collector:\n  enabled: %v\n\n", a.collectorNeeded())
	fmt.Fprintf(&b, "opentelemetry-operator:\n  enabled: %v\n\n", a.SDKAgent)
	fmt.Fprintf(&b, "gpuMonitoring:\n  enabled: %v\n", a.GPU)

	if a.Traces && !a.SDKAgent {
		b.WriteString("\n# Traces without SDK/agent instrumentation means eBPF (OBI). This chart\n")
		b.WriteString("# doesn't deploy OBI itself (a standalone Helm release, bring-your-own) --\n")
		b.WriteString("# see docs/getting-signals-into-grafana.md for a verified install command.\n")
	}
	if a.GPU {
		b.WriteString("\n# gpuMonitoring.enabled only adds a ServiceMonitor + PrometheusRule --\n")
		b.WriteString("# dcgm-exporter itself is bring-your-own (the NVIDIA GPU Operator's job, not\n")
		b.WriteString("# this chart's). See README's GPU section before turning this on.\n")
	}

	return b.String()
}

// resourceEstimate renders the same real, measured-on-a-cluster numbers from
// README's "Resource requirements" table, filtered to what these answers
// actually turn on -- so the whole point of asking ("this saves real
// compute") is visible immediately, not just implied.
func resourceEstimate(a initAnswers) string {
	type row struct {
		name       string
		cpu, mem   int // milli-CPU, Mi -- single-scheduled
		perNodeCPU int // milli-CPU -- 0 if not a DaemonSet
		perNodeMem int
	}
	var rows []row
	if a.Metrics {
		rows = append(rows, row{"kube-prometheus-stack (Prometheus, Alertmanager, Grafana, kube-state-metrics)", 245, 592, 0, 0})
		rows = append(rows, row{"node-exporter", 0, 0, 10, 24})
	}
	if a.SDKAgent {
		rows = append(rows, row{"OTel Operator", 30, 64, 0, 0})
	}
	if a.collectorNeeded() {
		rows = append(rows, row{"OTel Collector", 40, 256, 0, 0})
	}
	if a.Logs {
		rows = append(rows, row{"Loki (SingleBinary)", 10, 128, 0, 0})
		rows = append(rows, row{"logsCollector (pod-log shipping)", 0, 0, 50, 256})
		rows = append(rows, row{"loki-canary", 0, 0, 10, 24})
	}
	if a.Traces {
		rows = append(rows, row{"Tempo", 10, 128, 0, 0})
		if !a.SDKAgent {
			rows = append(rows, row{"OBI (eBPF probe, bring-your-own)", 0, 0, 10, 256})
		}
	}

	var totalCPU, totalMem, perNodeCPU, perNodeMem int
	var b strings.Builder
	fmt.Fprintln(&b, "\nEstimated footprint (single-scheduled + per-node, from this session's")
	fmt.Fprintln(&b, "own measurements against a real cluster -- see README's resource table):")
	for _, r := range rows {
		if r.cpu > 0 || r.mem > 0 {
			fmt.Fprintf(&b, "  %-70s %4dm  %5dMi\n", r.name, r.cpu, r.mem)
			totalCPU += r.cpu
			totalMem += r.mem
		} else {
			fmt.Fprintf(&b, "  %-70s %4dm  %5dMi  (per node)\n", r.name, r.perNodeCPU, r.perNodeMem)
			perNodeCPU += r.perNodeCPU
			perNodeMem += r.perNodeMem
		}
	}
	fmt.Fprintf(&b, "\n  Total: ~%dm CPU / ~%dMi RAM, plus ~%dm CPU / ~%dMi RAM per node.\n", totalCPU, totalMem, perNodeCPU, perNodeMem)
	return b.String()
}

func runInit(outPath string) error {
	if outPath == "" {
		outPath = "values-init.yaml"
	}
	if _, err := os.Stat(outPath); err == nil {
		return fmt.Errorf("%s already exists; pass -o to write somewhere else", outPath)
	}

	answers, err := runInitPrompts(os.Stdin, os.Stdout)
	if err != nil {
		return fmt.Errorf("reading answers: %w", err)
	}

	if err := os.WriteFile(outPath, []byte(renderValues(answers)), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}

	fmt.Println(resourceEstimate(answers))
	fmt.Printf("\nWrote %s. Next:\n\n", outPath)
	fmt.Printf("  helm install lantern charts/lantern-stack \\\n")
	fmt.Printf("    -f charts/lantern-stack/values-quickstart.yaml \\\n")
	fmt.Printf("    -f %s\n", outPath)
	return nil
}
